### ISSUE TITLE
Port to SKSE 2.0.7

### ISSUE THREAD

**Issue by ryobg** [ryobg/JContainers#18]
Looks like new update landed recently.

**Comment by RealAntithesis** [comment]
Thanks for looking at a port. I've had one AH Hotkeys user comment that it no longer works with the updated Skyrim SE and SKSE 2.07. I haven't tried myself since my Skyrim SE hasn't updated. I think something happened in Steam, because it's showing Skyrim SE as greyed out as if it's not installed. Looks like I'll need to reinstall / revalidate and get it all set up again...

**Comment by ryobg** [comment]
Let kick off first #19 before going on this as I expect to be a hassle to merge later if done the other way around.

**Comment by ryobg** [comment]
Release published at https://github.com/ryobg/JContainers/releases/tag/v4.1.0

**Comment by Neondaze** [comment]
Brilliant!. Thank you for your excellent work with this.
