### ISSUE TITLE
Log file location and missing folder

### ISSUE THREAD

**Issue by pugwash99** [ryobg/JContainers#2]
Log file is going to the Oldrim folder,

Line 120 skse_callbacks.cpp '"\\My Games\\Skyrim\\SKSE\\' needs changing to '"\\My Games\\Skyrim Special Edition\\SKSE\\'

Post install is also not creating the 'Domains' folder under 'Data\SKSE\Plugins\JCData'  - willl cause a ctd when starting skyrim if missing.

**Comment by ryobg** [comment]
Hey thanks! Will check these out. That "Domain" thing somehow I missed, or is it new for SSE? Anyway, will add it (really suprising that missing folder can cause CDT - lol).

**Comment by javierhimura** [comment]
The domain folder is not new for SSE, i check the nexus download from Oldrim and JContainers zip already contains an empty Domain folder, that is enought to fix the error, and it is better that the dll to create the folder for the first time because a player using Mod Organizer will ends with the folder in their overwrite folder instead the JContainers mod
I assume the author include the empty folder to the zip manually and that is why the post-build project does not add that folder to the zip

**Comment by ryobg** [comment]
I added auto-creation of this folder inside the distro archive. Do you think it will work like that for Mod Organizer?

**Comment by ryobg** [comment]
Btw, I just tested to load SSE with the plugin, it seems it registers ok. Actual use cases would be better.

**Comment by ryobg** [comment]
Bummer. Nexus Mod Manager ignores happily that empty Domains folder. There should be something dummy there, ignored during domain search. Or that folder is created at run-time which I see as a possible issue if it fails.

**Comment by ryobg** [comment]
I feel a bit ashamed of such solution. But nothing better comes to my mind currently.

**Comment by javierhimura** [comment]
That will explain the weird empty folder that is inside the zip from the version of Oldrim in Nexus
It has an empy Domain folder with another empty folder "JContainers_DomainExample" inside and inside there is another empty folder "dummy-file". Probably the last one is the only ignored by NMM

**Comment by ryobg** [comment]
I have checked too for path references, but its hard to find something else.
