### ISSUE TITLE
Deploy on Nexus?

### ISSUE THREAD

**Issue by ryobg** [ryobg/JContainers#22]
I will drop some notes here to ponder on. People also can express their opinion.

Pros:
1. More people can benefit or ease their life with JC
2. Mod friendly environment to install & support JC
3. More or less attracting development resources... and life into this project.

Cons:
1. My understanding is a bit low in terms of Skyrim modding, so I won't be able to support many cases.
2. Speculation: growing frustration out of 1.) eventually sinking JC.

**To be continued...**

**Comment by SilverIce** [comment]
Problem #1 I had in the past is that most of Skyrim modders aren't programmers.
Port some popular mods may bring the life to the project as well (?)

**Comment by ryobg** [comment]
I heard for several ported mods (users of JC) so you can say - life. But the truth is that many of them were just rushed over, so not much of JC knowledge was needed anyway. 

I agree also and with the "programmer" part. So far more "advanced" users were involved and this was fruitful experience. Part of the reason the JC distro is still here and it requires experienced modders as users.

**Comment by aers** [comment]
You'll probably end up with a lot of false positive bug reports from people who believe JContainers is somehow breaking things completely unrelated to its functionality... but that's just how things are, I guess.

IMO there's a net positive to releasing on Nexus. You can also disable bug reports on the mod on Nexus which might reduce the number of bad bug reports since the average person isn't going to come over here to report/discuss issues. 

I guess there's a fear that by releasing on Nexus you might feel an obligation to update for future SSE patches but no one has a right to make that demand. Also, JContainers only hooks 3 functions that aren't already covered by SKSE, right? Updating it for future versions is something a lot of devs could do if needed.

**Comment by ryobg** [comment]
Hi @aers, thanks for chimming in. 

Yes, it is not big deal so far to port over newer SKSE. I even have started a [documentation project](https://github.com/ryobg/JContainers/wiki/Development) for maintainers :+1: 

Another thing is that if there is more generic board, like Nexus, you will have what I called mod friendly environment i.e. while there will be a lot of noise, but there will be also people which help each other.

Well... I see I'm more inclined to deploy there, but not sure when. Maybe wait a bit to gather more feedback for the latest version.

**Comment by RealAntithesis** [comment]
I think uploading to the Nexus is a good idea when ready. It's more friendly to modders who are already used to downloading from the Nexus and this is more directly supported by more managers, especially when looking for updates. 

Github may not be familiar to most users and Jcontainers itself may not be perceived as a 'proper' or generally accepted mod (or modding resource) unless it is also on the Nexus.

While it's probably not a competition (or maybe it is, I don't know), PapyrusUtils is on the Nexus, so may naturally result in a greater mindshare among users and potential mod authors.

**Comment by ryobg** [comment]
Ok, thanks all. Nexus will be.

**Comment by ryobg** [comment]
FYI: https://www.nexusmods.com/skyrimspecialedition/mods/16495
I tried for first time
