### ISSUE TITLE
Can we get a release for SKSEVR?

### ISSUE THREAD

**Issue by VernMcC** [ryobg/JContainers#24]
SKSEVR was just released. The source code for it is in the release. I am hoping a SKSEVR is as simple as using that source code for a dll build instead of the SKSE64 source.  Either way, thank you for considering the request.

**Comment by ryobg** [comment]
Thanks for the info, and I will check it out to see what this may involve. Also we will need a tests volunteers as I have no VR setup.

**Comment by ryobg** [comment]
P.S. I had a quick look and most notably there is some changes how mods collections is handled, most notably there is a cut into the ESL mods support, then some trivial relocations and some new features which looks not relevant to JC. 

So... it would be easy, but(!) the new SKSE has to be integrated into the current project, some paths adjusted and I have to check further down their project configuration. It is mostly work wrt to configuration and maintenance, but still important.

**Comment by VernMcC** [comment]
I am trying to do that, but I am getting some build errors on just the instructions provided, so I cannot begin to figure out the changes until I figure out what dust I have to clean up to get the current code to build.  Thank you for your time and attention.

**Comment by VernMcC** [comment]
Fair warning, I just had to download new code for SKSEVR because a CTD bug was already squashed.

**Comment by ryobg** [comment]
Let me know if I can give some instruction to build the code. Should be more or less straightforward. Of course, I may havemissed some requirement or a step, but in this case, let me know so that documentation can be fixed.

Thanks for the warning. Will download again the latest. These days I won't have much time to look at this port, so if you like to build for yourself - will be nice, go ahead. Then if you would like also to submit a Merge/Pull request into some dev branch - feel invited again :+1:

**Comment by ryobg** [comment]
I want to extend the circle of testers, so I instead published a placeholder for incremental test releases of the VR edition: https://github.com/ryobg/JContainers/releases

You can find and download from there.
