### ISSUE TITLE
Add support for SKSE 2.1.5 / Skyrim SE 1.6.353

### ISSUE THREAD

**Issue by akanwischer** [ryobg/JContainers#88]
Version 1.6.353 was released on 6 January 2021, so unfortunately a new version is necessary. SKSE has already been updated.

Thanks for your effort!

**Comment by LordNikon22** [comment]
Just wanted to say thanks for your efforts.

**Comment by zacharywine** [comment]
Here's the answer to why things are not working lol! I picked a bad moment to reinstall Skyrim after years and truly  mod for the first time.

Thanks y'all for your efforts!

**Comment by DaveSoler88** [comment]
Someone can tell me how much time this can take to release a new version? Just because I already have the update of Skyrim, the new version of SKSE and now only need this new version of Jcontainers, and Im really need to play! I was having so much fun! Thank you.

**Comment by Ghostwalker71** [comment]
@DaveSoler88 It all depends on how soon ryobg is able to find a bit of time to update the files, he's generally on top of things but Life do get busy at times. I would guess it will probably be a day or three.

**Comment by DaveSoler88** [comment]
@Ghostwalker71 Okay great, thats is not too much time, thanks for the reply ghost, and thanks to ryobg for the effort!

**Comment by notprime** [comment]
Hello boys, a stupid question, never downloaded JContainers through github: what file do I have to download?

**Comment by ryobg** [comment]
> Hello boys, a stupid question, never downloaded JContainers through github: what file do I have to download?

GitHub Pre-releases are only for people who want to *test* the release. A technical expertise enables them to make better this software. Working with GitHub is mandatory knowledge if you want to be a tester. I'm just saying this if you are targeting the current 4.2.2 Pre-release.

Otherwise, the GitHub releases can be found on: https://github.com/ryobg/JContainers/releases - you can press on the banner-like counter button or under the Assets text expand menu.

And lastly, the recommended way of obtaining releases is through the Nexus Mods website: https://www.nexusmods.com/skyrimspecialedition/mods/16495/?tab=files

**Comment by artig4n** [comment]
New version doesn't work for me, Skyrim just exits without an error message. I updated AE yesterday and got the latest SKSE and this new Jcontainers, and now it's busted lol. I was enjoying that game, too.

**Comment by notprime** [comment]
> New version doesn't work for me, Skyrim just exits without an error message. I updated AE yesterday and got the latest SKSE and this new Jcontainers, and now it's busted lol. I was enjoying that game, too.
Other mods could cause the crash if not updated. Make sure all of your mods are updated before trying to launch the game.

**Comment by artig4n** [comment]
Ignore me, I'm a doofus. It's not Jcontainers causing my problems.
